title: Ruby Yagi 🐐
description: Ruby, Rails, Web dev articles
author: Axel Kee
url: https://rubyyagi.com

highlighter: rouge
permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml
